 #ifndef _AW889X_REG_TABLE_H_
 #define _AW889X_REG_TABLE_H_
#include "aw889x.h"
#include "aw889x_reg.h"

#define REG_NONE_ACCESS 0
#define REG_RD_ACCESS  1 << 0
#define REG_WR_ACCESS  1 << 1

const unsigned char aw889x_reg_access[AW889X_REG_MAX]={
  [AW889X_REG_ID]= REG_RD_ACCESS,
  [AW889X_REG_SYSST]= REG_RD_ACCESS,
  [AW889X_REG_SYSINT]= REG_RD_ACCESS,
  [AW889X_REG_SYSINTM]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_SYSCTRL]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_I2SCTRL]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_I2STXCFG]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_DSPCFG]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_PWMCTRL]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_HAGCCFG1]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_HAGCCFG2]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_DBGCTRL]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_I2SCFG]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_I2SSTAT]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_I2SCAPCNT]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_DSPMADD]= REG_NONE_ACCESS,
  [AW889X_REG_DSPMDAT]= REG_NONE_ACCESS,
  [AW889X_REG_WDT]= REG_RD_ACCESS,
  [AW889X_REG_GENCTRL]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_BSTCTRL]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_PLLCTRL1]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_PLLCTRL2]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_TESTCTRL]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_AMPDBG1]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_AMPDBG2]= REG_RD_ACCESS|REG_WR_ACCESS,
  [AW889X_REG_BSTDBG1]= REG_RD_ACCESS|REG_WR_ACCESS,

};

#endif
